function hRD = plugin_rd()
% Reference design definition

% Construct reference design object
hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Xilinx Vivado');

hRD.ReferenceDesignName = 'Demo system';
hRD.BoardName = 'kv260';

% Tool information
hRD.SupportedToolVersion = {'2024.1'};

% add custom Vivado design
hRD.addCustomVivadoDesign( ...
    'CustomBlockDesignTcl', 'design_1.tcl', ...
    'VivadoBoardPart','xilinx.com:kv260_som:part0:1.4');

hRD.addIPRepository(...
    'IPListFunction', 'kv260.kv260_ip');

% Add constraint files
hRD.CustomConstraints = {'constraints.xdc'};

%% Add interfaces
% add clock interface
hRD.addClockInterface( ...
  'ClockConnection',   'zynq_ultra_ps_e_0/pl_clk0', ...
  'ResetConnection',   'rst_ps7_0_50M/peripheral_aresetn');

% add AXI4 and AXI4-Lite slave interfaces
hRD.addAXI4SlaveInterface( ...
    'InterfaceConnection', 'ps7_0_axi_periph/M05_AXI', .....
    'BaseAddress',         '0xA0060000', ...
    'MasterAddressSpace',  'zynq_ultra_ps_e_0/Data');
     
% add AXI4-Stream interface
hRD.addAXI4StreamVideoInterface( ...
    'MasterChannelEnable',      true, ...
    'SlaveChannelEnable',       true, ...
    'MasterChannelConnection', 'axi_vdma_2/S_AXIS_S2MM', ...
    'SlaveChannelConnection',  'axis_broadcaster_0/M00_AXIS', ...
    'MasterChannelDataWidth',   64, ...
    'SlaveChannelDataWidth',    64);